[package]
edition = "2021"
name = "egg-smol"
version = "0.1.0"

[workspace]
members = [".", "web-demo"]

[features]
default = ["bin"]

bin = ["dep:clap", "dep:env_logger"]
wasm-bindgen = ["instant/wasm-bindgen"]

[dependencies]
hashbrown = {version = "0.13", features = ["raw"]}
indexmap = "1.9"
instant = "0.1"
log = "0.4"
rustc-hash = "1.1"
symbol_table = {git = "https://github.com/mwillsey/symbol_table", rev = "acddcf8938d1b4ed2fce048c9d83c30203d404b9", features = ["global"]}
thiserror = "1"
# symbol_table = { version = "0.2", features = ["global"] }
# symbol_table = { path = "../symbol_table", features = ["global"] }
lazy_static = "1.4"
num-integer = "0.1.45"
num-rational = "0.4.1"
num-traits = "0.2.15"
num = "0.4.0"
smallvec = "1.10"
#intervals-good = { git = "https://github.com/oflatt/intervals-good", rev = "6478b8f49245fc9a5177dd51b4fbd5d71be50852" }
intervals-good = { path = "../../../../intervals-good" }
rug = { version = "1.16.0", features = ["num-traits"]}
ordered-float = "3.4.0"
symbolic_expressions = { git = "https://github.com/oflatt/symbolic-expressions", rev = "4c0ea5ca008f972450b2af72387e64d2c1c6a791" }

lalrpop-util = {version = "0.19.8", features = ["lexer"]}
regex = "1"

# binary dependencies
clap = {version = "4", features = ["derive"], optional = true}
env_logger = {version = "0.10", optional = true}



[build-dependencies]
glob = "0.3.1"
lalrpop = "0.19.8"
